# Generated by Django 5.0.3 on 2024-03-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_news", "0003_alter_article_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
