# Generated by Django 5.0.3 on 2024-03-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_news', '0007_remove_article_publisher_article_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='pseudonym',
        ),
    ]
