# Generated by Django 4.2.4 on 2024-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_news", "0009_article_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-pub_date"]},
        ),
    ]
